# To use the Guardfile, simply 'gem install guard' and then run
# the 'guard' command from within the root of the viz directory.
# This will rebuild the project any time env.yml or anything inside
# of dev/ changes.

# More info at https://github.com/guard/guard#readme
require 'guard/guard'

module ::Guard
  class Vizr < ::Guard::Guard
    def run_all; end

    # Rebuild the project any time env.yml or anything in dev/ changes.
    def run_on_change(paths)
      puts `vizr build --dev .`
      puts "\e[1;32;40m ----- Built at #{Time.now.to_s}\e[0m\n\n"
    end
  end
end

guard 'vizr' do
  watch(%r{dev/.*|env.yaml})
end
